version: "3.7"
services:
  api_service:
    build: .
    restart: always
    ports:
      - 9090:9090
    depends_on:
      - mongo_db
  mongo_db:
    image: mongo
    restart: always
    ports:
      - 27017:27017