version: "3.8"
services:
  mongo-database:
    image: mongo
    container_name: mongo-on-docker
    restart: unless-stopped
    hostname: mongo-database
    ports:
      - 27017:27017
    volumes:
      - ./data/db:/data/db
    networks:
      - test-network

  noticeboard:
    image: noticeboard
    build:
      dockerfile: Dockerfile
    container_name: noticeboard
    restart: on-failure
    hostname: localhost
    ports:
      - 9090:9090
    networks:
      - test-network
    links:
      - mongo-database
      - redis-database

  redis-database:
    image: redis
    build:
      dockerfile: Dockerfile
    container_name: redis
    restart: on-failure
    hostname: redis-database
    ports:
      - 6379:6379
    networks:
      - test-network

networks:
  test-network:
    driver: bridge
